### ISSUE TITLE
feat: support alternative block explorers

### ISSUE THREAD

**Issue by alecdwm** [TalismanSociety/talisman#1197]
### Todo

- [x] Add [Analog's block explorer URL](https://explorer.analog.one/) to [chaindata](https://github.com/TalismanSociety/chaindata/commit/7e29376b22834c35d2cd22b516f2915557605ed6?w=1#diff-fcee67c8e2690a3d457a621a587b7873c105e7b1ecab9ae78acee8d1e64a8161L487) for Analog chain
- [x] Add [Bittensor Scan](https://bittensor.com/scan) and [Taostats](https://kx.taostats.io/) block explorer URLs to [chaindata](https://github.com/TalismanSociety/chaindata/commit/7e29376b22834c35d2cd22b516f2915557605ed6?w=1#diff-fcee67c8e2690a3d457a621a587b7873c105e7b1ecab9ae78acee8d1e64a8161L487) for Bittensor chain
- [ ] Build utility function for direct linking to blocks, extrinsics and on-chain accounts which is explorer-agnostic
  - Most likely implementation: add a `switch case` for each explorer host

Note: a nice-to-have would be to derive a `label` for each block explorer based on its URL, so we can say `Open on Subscan` instead of `Open on Block Explorer` in the wallet UI

---

##### The steps in this quote have been completed, but are left here for reference:
> The `Chain` definition here has a `subscanUrl` property: [Chain.ts](https://github.com/TalismanSociety/talisman/blob/0e797f5c5769ac1741e02fea539c0a930aeed5c3/packages/chaindata-provider/src/types/Chain.ts#L25).  
> We need to rename that to something like `blockExplorerUrl`.
> 
> Then in [chaindata](https://github.com/talismansociety/chaindata) we need to add the `blockExplorerUrl` key wherever there's currently a `subscanUrl`.
> 
> For backwards compatibility, we should keep keep the existing `subscanUrl`s there.  
> Otherwise the current production release of the wallet will suddenly think no chains have a subscan url.

##### These steps are not yet completed:

Once that's done, we need to fix the wallet because it will still be (1): looking for the block explorer url using the `subscanUrl` key, and (2): it assumes that the url is in subscan format, like `https://polkadot.subscan.io/extrinsic/<extrinsic-id>`.

Other block explorers will have their own URL scheme, so we need a function which takes the block id, extrinsic id or account address as well as the `blockExplorerUrl` and it returns the full block explorer url to that entity.

Analog for example, has the form `https://explorer.analog.one/#/extrinsic/<extrinsic-id>`.

Some explorers (e.g. [Bittensor Scan](https://bittensor.com/scan)) don't have the capacity to link directly to an extrinsic.
In that case, it will be ideal to link to the user's account instead, e.g. https://bittensor.com/scan/address/5EsUrh9LWJ8eXqVYhq9QZpKMYytxjSLxhRKXf1BFgUPWeksW
